server:
  port: 8181

spring:
  profiles:
    active: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springdb
    username: root
    password: root
    
  jpa:
    show_sql: true